### PR TITLE
Use Lettuce for Orbit Messaging

### PR DESCRIPTION
**Pull request by tmccnnll**
Change Orbit messaging to use [Lettuce](https://github.com/lettuce-io/lettuce-core) instead of Redisson.

### CODE REVIEW

**Comment by JoeHegarty** [comment]
Thanks for this. Big change here so will take me a while to go through it all. Hope to get a chance to look tomorrow.

**Comment by ShawnTuatara** [comment]
Version number... Seems like this is a bit bigger than just a patch change. Worth identifying it as 1.3 or even 2.0 as it breaks existing implementations with the rename of the class?

**Comment by tmccnnll** [comment]
I agree that it's a significant change and probably warrants a bigger version number bump.

@JoeHegarty, what has been the strategy for this project regarding version number increases?

**Comment by JoeHegarty** [comment]
I think this would make most sense as 1.3.0. We don't usually bump the version until we cut the release though so don't need to worry about that right now.

**Comment by JoeHegarty** [comment]
I assume the main motivation for this change was performance? Do you have any info on what kind of gains you get?
Has this code been tested in failure scenarios? Such as recovery after a Redis node has been down or a DNS failover?
@tmccnnll

**Comment by tmccnnll** [comment]
The motivation for this was based on internal testing of the performance between the Lettuce and Redisson pub/sub implementations. We found that, compared to Lettuce, Redisson required more connections to the Redis server (up to an order of magnitude more) and used more CPU on both the application and the Redis server sides of the connection (more than double on both sides).

I have tested the failure scenario of a Redis node being down and then coming back up. The Lettuce client will re-subscribe to all previously subscribed channels if it loses and then regains its connection to a Redis node. I have not tested the failure scenario of a DNS failover.

**Comment by JoeHegarty** [comment]
Are your planned changes now in @tmccnnll?

**Comment by JoeHegarty** [comment]
Having discussed this a little more in-depth with @tmccnnll we've decided that we're not going to take this change at this time. 
There are plans to move even more of this project onto lettuce and given the potentially large impact of this change we think it's a better candidate to either merge all the changes at once and declare a new major version, or offer 2 Redis clustering libraries (Redisson and Lettuce) as separate projects and leave the decision with the integrator/user.

**Pull request closed without merging**
